### ISSUE TITLE
UCD Age: Custom enum type or Option<UnicodeVersion>?

### ISSUE THREAD

**Issue by behnam** [behnam/rust-unic#120]
Right now, we have Age as this:

<https://github.com/behnam/rust-unic/blob/72ca9a893373f1857bc6ab6440389dfdceea6f13/unic/ucd/age/src/age.rs#L36-L42>

1. It's nice to have this `CompleteCharProperty`, as it gives meaningful API like `is_assigned()` and `is_unassigned()`.

2. Another option is to convert this to a `PartialCharProperty`, which returns `None` if the char is `Unassigned`, and `Some(UnicodeVersion)` otherwise.

3. One more option would be to have it as `PartialCharProperty`, but the return type will be more following the UAX#44 spec: only having major and minor numbers. Basically, return value would be `Some(Age)`, with `Age` being similar to `UnicodeVersion`, but without minor number. Then, we can have transformations between `Age` and `UnicodeVersion`.

Option (3) makes it much more like other types in UCD, option (2) is a bit farther, and option (1), which is the current one, is the farthest from general approach here.

BUT, there's also the fact that option (1) looks nicer and more organic comparing to the other ones.

I'm filing this mostly because I need to figure out a way to provide a property-range contract for `Age`, and would be great if it's not just an empty contract.

Any ideas?

**Comment by CAD97** [comment]
This is not an easy question.

In the best case scenario, only _valid_ ages (currently [1.1, 2.0, 2.1, 3.0, 3.1, 3.2, 4.0, 4.1, 5.0, 5.1, 5.2, 6.0, 6.1, 6.2, 6.3, 7.0, 8.0, 9.0, 10.0]) are valid `Age`s. [Age is a Category type after all.](http://unicode.org/reports/tr44/#Age) (That would suggest it should be a `EnumeratedCharProperty`. It even has defined aliases in ProperyValueAliases.txt!)

So you'd have a `impl From<Age> for UnicodeVersion` and a `impl TryFrom<UnicodeVersion> for Age`.

Unfortunately, in order to create `Age`s for our components at constant time, (at least until `const fn` and `static_assert!` stabilize) the field(s) of `Age` have to be public. This means we cannot guarantee that our `Age` is valid accross the above domain.

But! If we treat it like the category type it is, but use a more rich typing behind the scenes, we might get something like the following:

```rust
#[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub struct Age {
    version_major: u16,
    version_minor: u16,
}

impl PartialCharacterProperty for Age;
impl EnumeratedCharacterProperty for Age {
    const fn all_values() -> &'static [Age] {
        &[
            Age { version_major: 1, version_minor: 1 },
            Age { version_major: 2, version_minor: 0 },
            // and so on
        ]
    }
}

impl Age {
    pub const fn new(version_major: u16, version_minor: u16) -> Age {
        let age = Age { version_major, version_minor };
        if !Age::all_values().contains(age) { static_assert!(false, "Attempt to construct invalid Age") }
        age
    }
}
```

This is clearly using multiple unstable features, though, so is not a viable option (and is also thrown together in only a few minutes of typing into a GitHub post submission box).

**Comment by behnam** [comment]
A previous discussion about `Age` was here: https://github.com/behnam/rust-unic/issues/23

IMHO, it is not actually a problem for the public fields allowing a non-UCD Age value to be created. Later, whenever we have `const new` and such, we can try preventing it, but not an issue for today, I would say.

Also, as part of the older version of `Age`, there was actually a partial mapping between UV and Age, both implemented using `try_into()`. `Unassigned` Age would return `None` for try-into-UV, and non-age UV would return `None` in reverse. We can bring them back if we decide to not use UV for Age. (Option 3)

**Comment by CAD97** [comment]
It makes sense for `Age` to be a wrapper around `UnicodeVersion`.

I suppose option 2.5 is `struct Age(UnicodeVersion); fn Age::of(char) -> Option<Age>`?

I think I'm (loosely) in favor of option 2.5. `Age` should be a distinct type from `UnicodeVersion`. In my opinion `Age` should be an assigned `Age` and we should avoid re-implementing the `Option` pattern. As for `is_assigned()`, I think that would be a `fn` on some `UnicodeCodepoint`, not one on `Age`.

**Comment by behnam** [comment]
I was thinking about something similar, as well, based on this logic: we have properties with named values (like Enumerated), for which `of()` returns one of those variants. Other properties are basically a *relationship* from a `char` to a value type.

Here, *Age*, which is *the first Unicode Version where code-points was assigned*, is a relationship into `UnicodeVersion`, and is only defined for a some characters (is Partial).

Now, for only existing similar property, CCC, we are using `struct CanonicalCombiningClass(u8)`, which is helpful because it allows having `is_not_reordered()` and `is_reordered()` (functions on the actual value), besides the contracted method `number()`, which gives access to the actual value.

If we want to take the same approach, the design is clear.

So, the question is: should we? Is there any reason to make `Age` just a trait/module (uninstantiable) to optionally map a char to a UnicodeVersion?

If we go with the newtype struct, we can have more goodies, like methods. But, do we really need *any*? I'm wondering what a method on `Age` could be, which doesn't apply to UV.

**Comment by behnam** [comment]
Okay, at least the *display* method of an Age value is a good reason to keep it as a newtype struct.

https://github.com/behnam/rust-unic/blob/99164db5dd8f909cd5b491dcd516b13b3356c6ea/unic/ucd/age/src/age.rs#L106-L113

I'm working on a diff. Will submit soon.

**Comment by behnam** [comment]
Okay, my `dev` branch has an incomplete diff for this: https://github.com/behnam/rust-unic/commit/b8184d36eecb4988366de67b95c9b6ba8ac31d31

Now I remember one reason that made me go with a Complete non-Option-based type: sorting! Basically, the current design would allow every codepoint to be compared with another one, age-wise. With `Option<Age(UnicodeVersion)>` that's actually much harder to do, AFAIK.

Do you think we can find a way to fix that in the new design?

**Comment by behnam** [comment]
Okay, with a bit of cheating, I got a stable diff out: https://github.com/behnam/rust-unic/pull/123

Now, I have mixed feelings about this. I'm fine with changing the ordering of this specific property, because it didn't feel 100% right in the first place.

But, I think that in general we want an `Option`-like type with `None` variant ordered **after** the `Some` variant. If so, then we can create a new similar type, like
```rust
#[derive(Eq, Ord, PartialEq, PartialOrd)]
enum Knowable { Known(T), Unknown }`)
```
which puts all `Unknown` values at the end.

In this path, this package looks interesting: https://docs.rs/optional/0.2.0/optional/

We can either use those concepts, or just take exactly the parts we need to satisfy the needs here, specifically all Partial property types.

What do you think?

**Comment by behnam** [comment]
@llogiq, since you have lots of experience in this area, do you have any recommendation for us here?

**Comment by behnam** [comment]
Okay, thinking out load more here: both for the sake of consistent API, and consistent behavior, we better to have an `Option`-like type with the ordering that we want, and use that for `Age` implementation.

So, a question would be: do we always want the same ordering for all partial properties? A `None` value always go at the end of the list, or should always go at the beginning.

I like how `Age` works in the diff, and it kind of tells me that we need both behaviors, meaning that we need a generic `Partial` type over `Option`-like types, one being `Option`, and another *ReverseOption*.

**Comment by CAD97** [comment]
If I'm being honest, I like `Optional`. (If you look at the implementation note for `UnicodeDataEntry`, I actually mention it by name! I also implemented `Optioned<char>`: <https://github.com/llogiq/optional/pull/19>)

Here's another option:

```rust
struct OrdOption<T>(Option<T>);
impl<T> Deref for OrdOption<T> { deref = self.0 }
impl<T: PartialOrd> PartialOrd for OrdOption<T> {}
impl<T> Into<Option<T>> for OrdOption<T> {}
impl<T> From<Option<T>> for OrdOption<T> {}
```

This should effectively work as an `Option` whenever it's wanted, but also allow us to define an ordering.

**Comment by llogiq** [comment]
I personally think that using an `Option` is fine here. While [optional](https://github.com/llogiq/optional) could give a small speed improvement, I'm not convinced that code is on the hot path and the speedups actually materialize for the use case. Remember that `Option` is a well-known standard API, so nobody reading it will look twice, plus (unlike optional's types) it can actually be used to filter iterators.

**Comment by CAD97** [comment]
Here's my proposal for a "clean" implementation (though using `impl Trait`):

```rust
trait OptionLike<T> {
    // Option's fn <https://doc.rust-lang.org/std/option/enum.Option.html>
    fn as_option(self) -> Option<T>;
}

struct RevOrdOption<T>(Option<T>);
impl<T> Ord for RevOrdOption<T> {}

impl<T> OptionLike<T> for Option<T> {}
impl<T> OptionLike<T> for RevOrdOption<T> {}

trait PartialCharProperty {
    fn of(char) -> impl OptionLike<Self>
}
```

But I agree with @llogiq here that sticking with `Option` if at all possible is better here.

**Comment by behnam** [comment]
Thanks for the inputs, @llogiq and @CAD97!

I agree that we probably cannot foresee all possible use-cases of the API in regards of ordering, and trying to optimize for those cases with the cost of not using the core types is not a good choice.

So, looks like we can review and land the PR for `Age`, and only need to document (and probably provide examples) on how ordering works out of the box and how it can be customized.

I should also note that, this could be *the only* UCD Partial property with numeric-like value (versions). I think all other numeric-like properties are Total properties, therefore there's no need to worry about ordering of `None`.
