### ISSUE TITLE
Add Conformance Test to ucd-normal component

### ISSUE THREAD

**Issue by behnam** [behnam/rust-unic#18]
Use the *extracted* data file for `DecompositionType` property to test conformance of the implementation.

Test source file:
http://www.unicode.org/Public/UCD/latest/ucd/extracted/DerivedDecompositionType.txt

NOTE: The test should also verify that the characters **not** listed in the file get `None` value for the property.

Similar conformance test code: https://github.com/behnam/rust-unic/blob/master/components/bidi/tests/conformance_tests.rs

**Comment by CAD97** [comment]
I can do this one!
