### ISSUE TITLE
Enact The Not Rocket Science Rule Of Software Engineering

### ISSUE THREAD

**Issue by CAD97** [behnam/rust-unic#33]
We should enforce [The Not Rocket Science Rule of Software Engineering] with the help of [bors].

The benefit of using bors is well hashed out in the Rust community. Let's bring the benefits to UNIC!

This does not have to be done right away, but I would suggest integrating with bors before 1.0.0.

[The Not Rocket Science Rule of Software Engineering]: https://graydon2.dreamwidth.org/1597.html
[bors]: https://bors-ng.github.io/

**Comment by behnam** [comment]
Absolutely! This will be resolved when we find a home for UNIC in one of the existing orgs with better devops infra. Stay tuned.

**Comment by behnam** [comment]
I have enabled @bors-ng (https://github.com/apps/bors) and here's the first PR merged with it: https://github.com/behnam/rust-unic/pull/96
