### ISSUE TITLE
Exclude tools, data and data-dependent tests/benches in packages

### ISSUE THREAD

**Issue by behnam** [behnam/rust-unic#34]
We should use the [Cargo `exclude`](http://doc.crates.io/manifest.html#the-exclude-and-include-fields-optional) option to not publish data files to crates.io, as they are usually very large and almost of no use for 99.99% of the callers.

See https://github.com/servo/unicode-bidi/issues/43 for report issue with publishing tests without data when published crate is being used in repackaging.

See also https://github.com/rust-lang/cargo/issues/4268 for current limits of the `exclude` syntax, and the changes coming.

**Comment by CAD97** [comment]
Is there a way to dry-run `cargo publish`?

Without being able to test it, this might work (though since (I think) `exclude` doesn't get inherited it would have to be applied to all packages):

```toml
exclude = ["data/**/*", "src/**/tests/*conformance*.rs"]
```

**Comment by behnam** [comment]
`cargo package` creates the `.crate` file, which is what gets uploaded to crates.io, and downloaded later for consumption. The output is saved as `target/package/<package-name>-<package-version>.crate`.
