### ISSUE TITLE
Pack all utils together in one crate: unic-utils

### ISSUE THREAD

**Issue by behnam** [behnam/rust-unic#50]
The reason for having separate crates for UNIC components is the large data size for some of them, which may not be needed in other parts. Specially, UCD components all having data of all sizes, and not all algorithms need all of that data.

That rule doesn't apply to utility code, which basically doesn't have any data tables. So, it doesn't bother to have all of them under one umbrella crate and not maintain multiple utils sub-crates.

What do you think?

**Comment by CAD97** [comment]
It makes sense to me.
