### ISSUE TITLE
[ucd/normal] [proposal] Allow ucd-normal to use mark information from ucd-category

### ISSUE THREAD

**Issue by CAD97** [behnam/rust-unic#53]
`unic-ucd-normal` has its own table of symbols with a general general category of `Mark`. This duplication from `unic-ucd-category` is by design because ucd/normal does not need the entire classification that ucd/category exposes.

However, when including `unic-ucd` or just happening to want ucd/category as well, this is then duplicated information.

Hence, the proposal, which has three resolution paths:

- Add a feature (say, `ucd-category`) to `unic-ucd-normal` that, if on, does not compile the libraries own category mark table, and instead implements `is_combining_mark` as `GeneralCategory::of(character).is_mark()`
- Through benchmarks and other measurements, show that adding ucd/category as an unconditional dependency of ucd/normal is a acceptable level of bloat to avoid data duplication
- Leave it the way that it is and just test it into oblivion to make sure the implementations are in agreement (do this anyway)

Of which I suggest the first.

**Comment by behnam** [comment]
Yeah, agreed. Adding a feature for it is the best first step. We can compare the build sizes later and decide if we want to drop the old implementation.

So, `unic-ucd-normal`'s `default` feature would stay empty.

For the shared table, you just need to name the feature `unic-ucd-category`, and having the component as *optional* dependency, it automatically means that this dependency should be enabled for this feature.
