### ISSUE TITLE
CharProperty: API to get all possible values, if applicable

### ISSUE THREAD

**Issue by behnam** [behnam/rust-unic#66]
Some properties, like `GeneralCategory` and `BidiClass`, are a flat enum, and having a type function returning all possible values of them can help with writing tests.

For example, having an iterator over GC values can reduce this test to 20 execs of the loop block, not all Unicode code points: https://github.com/behnam/rust-unic/blob/master/unic/ucd/category/tests/coverage_tests.rs

**Comment by calum** [comment]
I'm interested in this one, if it's not already being worked on. 

Just to clarify: as an example, you want a function to return all chars that are `GC::MathSymbol`. Or, do you want a function to return all chars that are `GC.is_letter()`.

**Comment by calum** [comment]
I've thought about it a bit more now and you actually want a function which takes a char and returns all the types it fits into? Do you want a different function for BidiClass and GeneralCategory, or one function to return all the possible values from both?

**Comment by behnam** [comment]
Thanks, @calum, for the interest. The thing is that I filed this issue as a tracker for the feature, which is going to be implemented by the macros @CAD97 and I are working on. We are building tools to auto-generate most of the code that's already manually-generated, so we don't have to maintain the little things, like the feature mentioned here, manually.

There are a couple of other good starter tasks that I recommend. Let me comment there for you.

**Comment by behnam** [comment]
We have the API in and there's an integration test using it, so we can track the implementation directly in the code.
